name: Zip and Upload Repository

on:
  workflow_dispatch:
    inputs:
      zip_name:
        description: 'The name of the zip file to upload'
        required: true
        default: 'repo.zip'
        type: string
      ignored_content:
        description: 'The files to ignore'
        required: false
        default: ''
        type: string
    #   server_url:
    #     description: 'Server URL to upload to'
    #     required: true
    #     type: string
    #   server_path:
    #     description: 'Path on server to upload to'
    #     required: true
    #     default: '/tmp'
    #     type: string
    #   server_token:
    #     description: 'Server token'
    #     required: true
    #     type: string

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
            if [ -n "${{ inputs.ignored_content }}" ]; then
              IFS=',' read -ra EXCLUDES <<< "${{ inputs.ignored_content }}"
              zip -r "${{ inputs.zip_name }}.zip" . -x "${EXCLUDES[@]}"
            else
              zip -r "${{ inputs.zip_name }}.zip" .
            fi

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.zip_name }}
          path: ${{ inputs.zip_name }}.zip
          if-no-files-found: error
          compression-level: 4
          retention-days: 1
          overwrite: true
          include-hidden-files: true

    #   - name: Upload to server
    #     if: inputs.server_url != ''
    #     run: |
    #       # Using curl to upload to server
    #       curl -X POST \
    #         -F "file=@${{ inputs.zip_name }}.zip" \
    #         -F "path=${{ inputs.server_path }}" \
    #         "${{ inputs.server_url }}/upload"
    #     env:
    #       SERVER_TOKEN: ${{ inputs.SERVER_TOKEN }}