name: Zip and Upload Repository

on:
  workflow_dispatch:
    inputs:
      zip_name:
        description: 'The name of the zip file to upload'
        required: true
        default: 'repo.zip'
        type: string
      ignored_files:
        description: 'The files to ignore'
        required: false
        default: '*.git*'
        type: string

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
            IFS=',' read -ra EXCLUDES <<< "${{ inputs.ignored_files }}"
            zip -r "${{ inputs.zip_name }}.zip" . -x "${EXCLUDES[@]}"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.zip_name }}
          path: ${{ inputs.zip_name }}.zip
          if-no-files-found: error
          compression-level: 4
          retention-days: 1
          overwrite: true
          include-hidden-files: true